"""create conversation tables

Revision ID: 478febe09917
Revises: 
Create Date: 2026-05-12 21:19:23.114336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '478febe09917'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memory',
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('memory', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('conversation_state',
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('rag_call_count', sa.Integer(), nullable=False),
    sa.Column('last_turn_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('conversation_trace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('turn_id', sa.String(length=255), nullable=True),
    sa.Column('input_ticket_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_memory_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memory_after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_rewriter_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('built_context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('initial_route', sa.String(length=100), nullable=True),
    sa.Column('nodes_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_rag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_trace_ticket_id'), 'conversation_trace', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_conversation_trace_turn_id'), 'conversation_trace', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_trace_turn_id'), table_name='conversation_trace')
    op.drop_index(op.f('ix_conversation_trace_ticket_id'), table_name='conversation_trace')
    op.drop_table('conversation_trace')
    op.drop_table('conversation_state')
    op.drop_table('conversation_memory')
    # ### end Alembic commands ###
