from __future__ import annotations

import os
from unittest.mock import MagicMock

import pytest

from src.agents.memory_agent import MemoryAgent
from src.core.memory_models import ConversationMemory, MemoryUpdateInput
from src.core.request_models import Ticket
from src.core.summary_models import SummaryOutput
from src.core.response_models import ResponseOutput


def make_memory_agent_without_llm() -> MemoryAgent:
    """
    Create a MemoryAgent instance without calling __init__.

    This avoids initializing ChatGoogleGenerativeAI in unit tests,
    so no GOOGLE_API_KEY/GEMINI_API_KEY is required.
    """
    return MemoryAgent.__new__(MemoryAgent)


def make_ticket(
    description: str = "My iPhone battery drains quickly after the latest update.",
) -> Ticket:
    return Ticket(
        ticket_id="ticket-001",
        turn_id="turn-001",
        source="test",
        description=description,
        domain="technical_support",
        subdomain="battery_life",
        product="iphone",
    )


def make_summary(
    problem: str = "The user reports fast battery drain after a recent iPhone update.",
    context: str = "The issue concerns battery life and may require troubleshooting steps.",
    intent: str = "Get help fixing the battery drain issue.",
) -> SummaryOutput:
    return SummaryOutput(
        problem=problem,
        context=context,
        intent=intent,
    )


def make_response(
    response: str = (
        "Please check battery health, update your apps, and reduce background activity. "
        "If the phone keeps overheating, contact support."
    ),
    resolution_type: str = "troubleshooting_steps",
    requires_escalation: bool = False,
    escalation_channel: str = "none",
) -> ResponseOutput:
    return ResponseOutput(
        response=response,
        tone="professional",
        resolution_type=resolution_type,
        requires_escalation=requires_escalation,
        confidence=0.8,
        escalation_channel=escalation_channel,
    )


def make_memory_update_input(
    previous_memory: ConversationMemory | None = None,
    ticket: Ticket | None = None,
    summary: SummaryOutput | None = None,
    response: ResponseOutput | None = None,
) -> MemoryUpdateInput:
    return MemoryUpdateInput(
        ticket=ticket or make_ticket(),
        previous_memory=previous_memory,
        summary=summary or make_summary(),
        response=response or make_response(),
    )


@pytest.fixture
def memory_agent() -> MemoryAgent:
    agent = make_memory_agent_without_llm()
    agent.structured_llm = MagicMock()
    return agent


def extract_message_contents(messages):
    return [message.content for message in messages]


# ---------------------------------------------------------------------
# Unit tests: update_memory behavior
# ---------------------------------------------------------------------


def test_memory_agent_returns_conversation_memory(memory_agent: MemoryAgent):
    expected_memory = ConversationMemory(
        memory=(
            "The user reports iPhone battery drain after a recent update. "
            "The assistant suggested checking battery health and reducing background activity."
        )
    )

    memory_agent.structured_llm.invoke.return_value = expected_memory

    memory_update_input = make_memory_update_input()
    result = memory_agent.update_memory(memory_update_input)

    assert isinstance(result, ConversationMemory)
    assert result == expected_memory
    assert result.memory
    memory_agent.structured_llm.invoke.assert_called_once()


def test_memory_agent_returns_result_from_structured_llm(memory_agent: MemoryAgent):
    expected_memory = ConversationMemory(
        memory="Updated memory for this support case.")
    memory_agent.structured_llm.invoke.return_value = expected_memory

    result = memory_agent.update_memory(make_memory_update_input())

    assert result is expected_memory


def test_memory_agent_invokes_structured_llm_with_messages(memory_agent: MemoryAgent):
    expected_memory = ConversationMemory(
        memory="Memory generated by mocked LLM.")
    memory_agent.structured_llm.invoke.return_value = expected_memory

    memory_agent.update_memory(make_memory_update_input())

    call_args = memory_agent.structured_llm.invoke.call_args
    assert call_args is not None

    messages = call_args.args[0]
    assert len(messages) == 2
    assert messages[0].type == "system"
    assert messages[1].type == "human"


# ---------------------------------------------------------------------
# Unit tests: prompt construction without previous memory
# ---------------------------------------------------------------------


def test_build_messages_without_previous_memory_does_not_include_previous_memory_block():
    agent = make_memory_agent_without_llm()
    memory_update_input = make_memory_update_input(previous_memory=None)

    messages = agent._build_messages(memory_update_input)
    system_prompt, human_prompt = extract_message_contents(messages)

    assert "Conversation Memory Agent" in system_prompt
    assert "There may or may not be previous conversation memory" in system_prompt

    assert "PREVIOUS CONVERSATION MEMORY" not in human_prompt
    assert "CURRENT USER MESSAGE" in human_prompt
    assert "CURRENT PROBLEM" in human_prompt
    assert "CURRENT CONTEXT" in human_prompt
    assert "ASSISTANT RESPONSE" in human_prompt
    assert "RESPONSE TYPE" in human_prompt
    assert "Create the first conversation memory" in human_prompt


def test_build_messages_without_previous_memory_includes_current_turn_fields():
    agent = make_memory_agent_without_llm()

    ticket = make_ticket(
        description="My phone gets hot when I open basic apps."
    )
    summary = make_summary(
        problem="The user reports that the phone gets hot when using basic apps.",
        context="The issue appears related to overheating during normal usage.",
        intent="Understand how to stop the phone from getting hot.",
    )
    response = make_response(
        response="Please close background apps and check whether the device still heats up.",
        resolution_type="troubleshooting_steps",
    )

    memory_update_input = make_memory_update_input(
        previous_memory=None,
        ticket=ticket,
        summary=summary,
        response=response,
    )

    messages = agent._build_messages(memory_update_input)
    human_prompt = messages[1].content

    assert ticket.description in human_prompt
    assert summary.problem in human_prompt
    assert summary.context in human_prompt
    assert response.response in human_prompt
    assert str(response.resolution_type) in human_prompt


def test_build_messages_without_previous_memory_has_memory_creation_task():
    agent = make_memory_agent_without_llm()
    memory_update_input = make_memory_update_input(previous_memory=None)

    messages = agent._build_messages(memory_update_input)
    human_prompt = messages[1].content

    assert "TASK:" in human_prompt
    assert "Create the first conversation memory from this turn" in human_prompt


# ---------------------------------------------------------------------
# Unit tests: prompt construction with previous memory
# ---------------------------------------------------------------------


def test_build_messages_with_previous_memory_includes_previous_memory_block():
    agent = make_memory_agent_without_llm()

    previous_memory = ConversationMemory(
        memory=(
            "The user has an ongoing iPhone battery drain issue after an update. "
            "The assistant suggested checking battery health."
        )
    )

    memory_update_input = make_memory_update_input(
        previous_memory=previous_memory)

    messages = agent._build_messages(memory_update_input)
    human_prompt = messages[1].content

    assert "PREVIOUS CONVERSATION MEMORY" in human_prompt
    assert previous_memory.memory in human_prompt
    assert "CURRENT USER MESSAGE" in human_prompt
    assert "Update the previous conversation memory" in human_prompt


def test_build_messages_with_previous_memory_has_update_task_not_creation_task():
    agent = make_memory_agent_without_llm()

    previous_memory = ConversationMemory(
        memory="The user previously reported an iPhone battery issue."
    )

    memory_update_input = make_memory_update_input(
        previous_memory=previous_memory)

    messages = agent._build_messages(memory_update_input)
    human_prompt = messages[1].content

    assert "Update the previous conversation memory using the current turn" in human_prompt
    assert "Create the first conversation memory from this turn" not in human_prompt


def test_build_messages_with_blank_previous_memory_treats_it_as_missing():
    agent = make_memory_agent_without_llm()

    previous_memory = ConversationMemory(memory="   ")
    memory_update_input = make_memory_update_input(
        previous_memory=previous_memory)

    messages = agent._build_messages(memory_update_input)
    human_prompt = messages[1].content

    assert "PREVIOUS CONVERSATION MEMORY" not in human_prompt
    assert "Create the first conversation memory from this turn" in human_prompt


def test_build_messages_with_previous_memory_includes_current_turn_fields():
    agent = make_memory_agent_without_llm()

    previous_memory = ConversationMemory(
        memory="The user has an unresolved iPhone overheating issue."
    )
    ticket = make_ticket(
        description="I checked battery health and it says 87%, but it still gets hot."
    )
    summary = make_summary(
        problem="The user checked battery health, which is 87%, but the phone still gets hot.",
        context="The issue remains unresolved after checking battery health.",
        intent="Continue troubleshooting an unresolved overheating issue.",
    )
    response = make_response(
        response="Since battery health is 87%, please check background activity and recent app updates.",
        resolution_type="troubleshooting_steps",
    )

    memory_update_input = make_memory_update_input(
        previous_memory=previous_memory,
        ticket=ticket,
        summary=summary,
        response=response,
    )

    messages = agent._build_messages(memory_update_input)
    human_prompt = messages[1].content

    assert previous_memory.memory in human_prompt
    assert ticket.description in human_prompt
    assert summary.problem in human_prompt
    assert summary.context in human_prompt
    assert response.response in human_prompt
    assert str(response.resolution_type) in human_prompt


# ---------------------------------------------------------------------
# Unit tests: system prompt safety and responsibility boundaries
# ---------------------------------------------------------------------


def test_system_prompt_defines_memory_agent_boundaries():
    agent = make_memory_agent_without_llm()
    messages = agent._build_messages(make_memory_update_input())

    system_prompt = messages[0].content

    assert "Do not answer the customer" in system_prompt
    assert "Do not generate new troubleshooting steps" in system_prompt
    assert "Do not mention internal pipeline details" in system_prompt
    assert "agents, prompts, tools, RAG, retrieval, chunks, or system decisions" in system_prompt


def test_system_prompt_requires_distinguishing_suggestions_from_user_actions():
    agent = make_memory_agent_without_llm()
    messages = agent._build_messages(make_memory_update_input())

    system_prompt = messages[0].content

    assert "Track what the user has already tried only when the user explicitly says they tried it" in system_prompt
    assert "Track what the assistant has suggested" in system_prompt
    assert "do not confuse suggestions with completed user actions" in system_prompt


def test_system_prompt_prioritizes_current_turn_over_previous_memory():
    agent = make_memory_agent_without_llm()
    messages = agent._build_messages(make_memory_update_input())

    system_prompt = messages[0].content

    assert "If the current turn contradicts previous memory, prioritize the current turn" in system_prompt


def test_system_prompt_requires_concise_english_memory():
    agent = make_memory_agent_without_llm()
    messages = agent._build_messages(make_memory_update_input())

    system_prompt = messages[0].content

    assert "Keep the memory concise, factual, and useful" in system_prompt
    assert "Write the memory in English" in system_prompt


# ---------------------------------------------------------------------
# Integration-style unit tests with mocked LLM
# ---------------------------------------------------------------------


def test_memory_agent_updates_existing_memory_with_mocked_llm(memory_agent: MemoryAgent):
    previous_memory = ConversationMemory(
        memory=(
            "The user has an iPhone battery drain issue after an update. "
            "The assistant suggested checking battery health."
        )
    )

    ticket = make_ticket(
        description="I checked battery health and it says 87%, but it still gets hot."
    )
    summary = make_summary(
        problem="The user checked battery health, which is 87%, but the iPhone still gets hot.",
        context="The previous memory indicates an ongoing battery drain and overheating issue.",
        intent="Continue troubleshooting because the issue persists.",
    )
    response = make_response(
        response=(
            "Since battery health is 87%, please check background app activity, "
            "update apps, and monitor whether the phone overheats."
        ),
        resolution_type="troubleshooting_steps",
    )

    expected_memory = ConversationMemory(
        memory=(
            "The user has an unresolved iPhone battery drain and overheating issue after an update. "
            "The user checked battery health and it is 87%. "
            "The assistant has suggested checking background app activity, updating apps, and monitoring overheating."
        )
    )

    memory_agent.structured_llm.invoke.return_value = expected_memory

    result = memory_agent.update_memory(
        make_memory_update_input(
            previous_memory=previous_memory,
            ticket=ticket,
            summary=summary,
            response=response,
        )
    )

    assert result == expected_memory

    messages = memory_agent.structured_llm.invoke.call_args.args[0]
    human_prompt = messages[1].content

    assert "PREVIOUS CONVERSATION MEMORY" in human_prompt
    assert previous_memory.memory in human_prompt
    assert ticket.description in human_prompt
    assert summary.problem in human_prompt
    assert response.response in human_prompt


def test_memory_agent_creates_first_memory_with_mocked_llm(memory_agent: MemoryAgent):
    ticket = make_ticket(
        description="My iPhone battery drains quickly after the latest update and gets warm."
    )
    summary = make_summary(
        problem="The user reports iPhone battery drain and warmth after the latest update.",
        context="The issue relates to battery life and possible overheating.",
        intent="Get troubleshooting help.",
    )
    response = make_response(
        response="Please check battery health, update apps, and reduce background activity.",
        resolution_type="troubleshooting_steps",
    )

    expected_memory = ConversationMemory(
        memory=(
            "The user reports that their iPhone battery drains quickly after the latest update "
            "and gets warm. The assistant suggested checking battery health, updating apps, "
            "and reducing background activity. The issue has not been confirmed as resolved."
        )
    )

    memory_agent.structured_llm.invoke.return_value = expected_memory

    result = memory_agent.update_memory(
        make_memory_update_input(
            previous_memory=None,
            ticket=ticket,
            summary=summary,
            response=response,
        )
    )

    assert result == expected_memory

    messages = memory_agent.structured_llm.invoke.call_args.args[0]
    human_prompt = messages[1].content

    assert "PREVIOUS CONVERSATION MEMORY" not in human_prompt
    assert "Create the first conversation memory" in human_prompt
    assert ticket.description in human_prompt


# ---------------------------------------------------------------------
# Optional live LLM tests
# ---------------------------------------------------------------------


requires_live_llm = pytest.mark.skipif(
    os.getenv("RUN_LIVE_LLM_TESTS") != "1",
    reason="Set RUN_LIVE_LLM_TESTS=1 to run live MemoryAgent tests.",
)


@requires_live_llm
def test_memory_agent_live_creates_first_memory():
    agent = MemoryAgent()

    ticket = make_ticket(
        description=(
            "My iPhone battery drains very quickly after the latest update "
            "and gets warm when I use basic apps."
        )
    )
    summary = make_summary(
        problem="The user reports fast iPhone battery drain and warmth after the latest update.",
        context="The issue concerns battery life and device warmth during basic app usage.",
        intent="Get troubleshooting help for battery drain and warmth.",
    )
    response = make_response(
        response=(
            "Please check battery health, update installed apps, reduce background app refresh, "
            "and monitor whether the device becomes unusually hot."
        ),
        resolution_type="troubleshooting_steps",
    )

    result = agent.update_memory(
        make_memory_update_input(
            previous_memory=None,
            ticket=ticket,
            summary=summary,
            response=response,
        )
    )

    assert isinstance(result, ConversationMemory)
    assert result.memory.strip()

    memory_lower = result.memory.lower()
    assert "iphone" in memory_lower
    assert "battery" in memory_lower
    assert "update" in memory_lower


@requires_live_llm
def test_memory_agent_live_updates_existing_memory():
    agent = MemoryAgent()

    previous_memory = ConversationMemory(
        memory=(
            "The user reports that their iPhone battery drains quickly after a recent update "
            "and the device gets warm. The assistant suggested checking battery health."
        )
    )

    ticket = make_ticket(
        description="I checked battery health and it says 87%, but the phone still gets hot."
    )
    summary = make_summary(
        problem="The user checked battery health, which is 87%, but the phone still gets hot.",
        context="The issue remains unresolved after checking battery health.",
        intent="Continue troubleshooting the unresolved overheating and battery issue.",
    )
    response = make_response(
        response=(
            "Since battery health is 87%, please check background activity, update apps, "
            "and monitor overheating. If it becomes too hot to touch, contact support."
        ),
        resolution_type="troubleshooting_steps",
    )

    result = agent.update_memory(
        make_memory_update_input(
            previous_memory=previous_memory,
            ticket=ticket,
            summary=summary,
            response=response,
        )
    )

    assert isinstance(result, ConversationMemory)
    assert result.memory.strip()

    memory_lower = result.memory.lower()
    assert "87" in memory_lower
    assert "hot" in memory_lower or "warm" in memory_lower
    assert "battery" in memory_lower


@requires_live_llm
def test_memory_agent_live_does_not_confuse_assistant_suggestion_with_user_action():
    agent = MemoryAgent()

    ticket = make_ticket(
        description="My iPhone battery drains quickly after the latest update."
    )
    summary = make_summary(
        problem="The user reports iPhone battery drain after the latest update.",
        context="The issue concerns battery life after a software update.",
        intent="Get help fixing the battery drain.",
    )
    response = make_response(
        response="Please restart the phone and check battery health.",
        resolution_type="troubleshooting_steps",
    )

    result = agent.update_memory(
        make_memory_update_input(
            previous_memory=None,
            ticket=ticket,
            summary=summary,
            response=response,
        )
    )

    memory_lower = result.memory.lower()

    assert "restart" in memory_lower or "battery health" in memory_lower

    forbidden_phrases = [
        "the user restarted",
        "user restarted",
        "the user has restarted",
        "the user checked battery health",
        "user checked battery health",
        "the user has checked battery health",
    ]

    assert not any(phrase in memory_lower for phrase in forbidden_phrases)


@requires_live_llm
def test_memory_agent_live_prioritizes_current_turn_over_previous_memory():
    agent = MemoryAgent()

    previous_memory = ConversationMemory(
        memory=(
            "The user previously reported an iPhone battery issue. "
            "The assistant suggested checking battery health."
        )
    )

    ticket = make_ticket(
        description=(
            "Actually, the problem is with my iPad, not my iPhone. "
            "The iPad battery drains fast."
        )
    )
    summary = make_summary(
        problem="The user clarifies that the issue is with an iPad battery draining fast, not an iPhone.",
        context="The current user message contradicts the previous memory about the affected product.",
        intent="Correct the product context and get help with the iPad battery issue.",
    )
    response = make_response(
        response="Thanks for clarifying. For the iPad, please check battery usage by app and update iPadOS.",
        resolution_type="troubleshooting_steps",
    )

    result = agent.update_memory(
        make_memory_update_input(
            previous_memory=previous_memory,
            ticket=ticket,
            summary=summary,
            response=response,
        )
    )

    memory_lower = result.memory.lower()

    assert "ipad" in memory_lower
    assert "battery" in memory_lower
